Repository ProjectSakura/ProjectSakura.github.io, pull requests merged in 2021-04, with the labels that each got.

#217 Validated blog.html
  blog.html
  css/blog.css
  css/main.css
Labels: gssoc21, level2

#219 updated the theme of downloads page
  download.html
  image/sakura_footer.svg
Labels: gssoc21, level3

#223 css reordered for index.html file
  index.html
Labels: gssoc21, level3

#227 documentation of filter.js
  js/filter.js
Labels: gssoc21, level2

#229 Added animation / transition to buttons
  css/blog.css
  css/style.css
Labels: gssoc21, level2

#228 reordered css elements for download.html
  download.html
Labels: gssoc21, level3

#234 Scroll Bar Color Updated
  css/css/style.css
  css/style.css
Labels: gssoc21, level2

#250 Align the images of Contact us page against issue #224
  css/style.css
  image/gmail_02.png
  image/telegram_02.png
  image/twitter_02.png
  index.html
Labels: gssoc21, level2

#254 Minor typos fix
  README.md
  index.html
Labels: gssoc21, level2

#256 Validate Stats
  stats.html
Labels: gssoc21, level1

#277 fixed header and footer issues
  stats.html
Labels: gssoc21, level3

#281 Addition of twitter link
  index.html
Labels: gssoc21, level0

#283 Scroll-top arrow added to website
  blog.html
  css/blog.css
  css/css/index/style.css
  index.html
  js/stat.js
  js/timeline.js
  stats.html
Labels: gssoc21, level3
