Repository ProjectSakura/ProjectSakura.github.io, pull requests merged in 2021-03, with the labels that each got.

#129 Solved hover issue
  css/style.css
  index.html
Labels: gssoc21

#143 updated readme file
  README.md
Labels: gssoc21, level 0

#145 Updated blog UI
  blog.html
  css/blog.css
  posts/3-R-android-11-beta-2.html
Labels: gssoc21, level3

#154 Fixed few errors on the css files
  css/bootstrap.css
  css/css/style.css
Labels: gssoc21, level3

#159 Updated the buttons on the blog page (according the UI guidelines)
  blog.html
  css/blog.css
Labels: gssoc21, level1

#170 Navbar update on all pages issue#148
  blog.html
  css/main.css
  css/style.css
  download.html
  index.html
Labels: gssoc21, level3

#172 deleted logs
  js/stat.js
  js/test2.js
Labels: gssoc21, level1

#178 default dark theme and added toggle btn
  stats.html
Labels: gssoc21, level1, level2, level3

#184 Home page btns updated
  css/style.css
Labels: gssoc21, level1

#196 improved UI elements in downloads page
  css/main.css
  download.html
Labels: gssoc21, level2, level3

#201 Added back to top button in index.html
  index.html
Labels: gssoc21, level3

#204 Added hover effects and refactored some colors in footer
  css/main.css
Labels: gssoc21, level3

#207 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc21, level2

#203 Added hover effects in footer of homepage
  css/style.css
  index.html
Labels: gssoc21, level2

#210 validated stats page
  stats.html
Labels: gssoc21, level3
